version: "3.8"

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ekene"
    ports:
      - "5432:5432"